# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
      kernelModules = [];
      luks.devices."cryptroot" = {
        device = "/dev/disk/by-uuid/3e312bff-651d-4ac0-91a2-89165825e544";
        allowDiscards = true;
      };
    };
    kernelModules = ["kvm-amd"];
    extraModulePackages = [];
  };

  services.fstrim.enable = true;

  fileSystems = {
    "/" = {
      device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = ["subvol=@" "compress=zstd" "noatime"];
    };

    "/home" = {
      device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = ["subvol=@home" "compress=zstd" "noatime"];
    };

    "/nix" = {
      device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = ["subvol=@nix" "compress=zstd" "noatime"];
    };

    "/var/log" = {
      device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = ["subvol=@log" "compress=zstd" "noatime"];
    };

    "/swap" = {
      device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = ["subvol=@swap" "compress=zstd" "noatime" "nofail"];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/12CE-A600";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };

    "/data" = {
      device = "/dev/mapper/data";
      fsType = "btrfs";
      options = ["subvol=@data" "compress=zstd" "noatime" "nofail"];
    };
  };

  environment.etc.crypttab.text = ''
    data /dev/disk/by-partlabel/cryptdata /root/keys/data.key luks,nofail
  '';

  swapDevices = [{device = "/swap/swapfile";}];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
