# Mango configuration.
# Docs: mangowm configuration/bindings/visuals/rules and Noctalia Mango keybind examples.
source=./config/animations.conf
source=./config/autostart.conf
source=./config/env.conf
source=./config/input.conf
source=./config/keybinds.conf
source=./config/layouts.conf
source=./config/looknfeel.conf
source=./config/misc.conf
source=./config/monitors.conf
source=./config/windowrules.conf
